// services/discoveryPipeline.ts
//
// Orchestrates the complete website discovery process end-to-end.
//
// Pipeline:
//   runDiscoveryPipeline(keyword)
//     ├── Step 1: discoverWebsites()     — find URLs via mock/Google/Bing
//     ├── Step 2: crawlWebsite()         — visit each URL with Playwright
//     ├── Step 3: (from crawl result)    — detect free listing signals
//     ├── Step 4: classifyIndustry()     — keyword or OpenAI classification
//     ├── Step 5: getMozMetrics()        — fetch real DA and spam scores
//     ├── Step 6: categorizeDa()         — map DA number → Low/Average/Excellent
//     ├── Step 6: createWebsite()        — persist to database (skipped if DB down)
//     └── Return: PipelineReport

import { discoverWebsites, scoreDirectoryCandidate } from "@/services/discoveryService";
import { crawlWebsite, closeBrowser } from "@/services/crawlerService";
import { classifyIndustry }           from "@/services/industryClassifier";
import { saveDiscoveredWebsite }      from "@/services/websiteService";
import { getMozMetrics }              from "@/services/mozService";
import { DaCategory }                 from "@prisma/client";
import { mapConcurrent }              from "@/lib/concurrency"; // Import centralized mapConcurrent
import { logger }                     from "./logger";
import { formatDateSafe }             from "./dateUtils";

// ─── Types ────────────────────────────────────────────────────────────────────

/** Shape returned by the pipeline — matches the Website UI interface exactly. */
export interface PipelineResult {
  id: string;
  name: string;
  url: string;
  description: string | null;
  domainAuthority: number;
  spamScore: number;
  freeListing: boolean;
  industry: string;
  daCategory: "Low" | "Average" | "Excellent";
  estimatedTraffic: number;
  contactEmail: string | null;
  socialLinks: Record<string, string> | null;
  active: boolean;
  freeOrPaid: string;
  canSubmitListing: boolean;
  submissionUrl: string | null;
  verificationMethod?: string;
  category: string;
  supportsSelfSubmission: boolean; // New field for Stage 5
  matchReason: string; // New field for Stage 5
  citationScore: number;
  isAggregator: boolean;
  requiresVpn: boolean;
}

export interface PipelineOptions {
  /**
   * When true, skips the database save step (Step 6).
   * Useful for dry-run / preview mode without persisting anything.
   * Default: false
   */
  dryRun?: boolean;
}

export interface PipelineReport {
  keyword: string;
  /** Total URLs returned by the discovery step. */
  discovered: number;
  /** URLs successfully processed through the full pipeline. */
  processed: number;
  /** URLs successfully saved to the database. */
  saved: number;
  /** URLs that failed processing and were skipped. */
  failed: number;
  results: PipelineResult[];
  /** Discovery source provider name. */
  source: string;
  /** True if results were generated by a mock or fallback provider. */
  isFallback: boolean;
  startedAt: string;
  completedAt: string;
  diagnostics?: {
    providerSelected: string;
    urlsDiscoveredCount: number;
    urlsFilteredCount: number;
    urlsCrawledCount: number;
    urlsSavedCount: number;
    crawlSuccessRatePercent: number;
    saveSuccessRatePercent: number;
    discoveredBlogs?: number;
    discoveredDirectories?: number;
    discoveredBusinessSites?: number;
  };
}

// ─── DA categorisation ────────────────────────────────────────────────────────

/**
 * Maps a numeric Domain Authority score to a category label.
 *
 * Ranges:
 *   0–20   → Low
 *   21–50  → Average
 *   51–100 → Excellent
 */
export function categorizeDa(da: number): "Low" | "Average" | "Excellent" {
  if (da <= 20) return "Low";
  if (da <= 50) return "Average";
  return "Excellent";
}

// ─── Per-URL processor ────────────────────────────────────────────────────────

/**
 * Runs steps 2–6 for a single discovered URL.
 * Returns null if the URL itself is invalid, fails to load, or has empty content.
 */
async function processUrl(
  discoveredUrl: string,
  discoveredTitle: string,
  index: number,
  total: number,
  dryRun: boolean,
  rankPosition?: number,
  sourceProvider?: string,
  type?: "listingOpportunity"
): Promise<PipelineResult | null> {
  logger.info(`[Pipeline] [${index}/${total}] ${discoveredUrl}`);

  // ── Step 2: Crawl the website with Playwright ──────────────────────────────
  logger.info(`  Websites crawled — ${discoveredUrl}…`);
  const crawl = await crawlWebsite(discoveredUrl);

  if (crawl.error) {
    logger.warn(`  Crawl failed (${crawl.error}) — skipping`);
    return null;
  }

  if (!crawl.homepageText || !crawl.homepageText.trim()) {
    logger.warn(`  Empty content returned — skipping`);
    return null;
  }

  logger.info(`  Crawled — title: "${crawl.title}"`);

  // ── Blocked/geo-restricted site detection ─────────────────────────────────
  // Reject pages that are geo-blocked, access-denied, or Cloudflare-challenged
  // because they contain no usable content and would pollute the directory index.
  // Cloudflare challenge pages are rejected because they indicate the crawler
  // cannot access the real content. Geo-restricted sites are rejected because
  // they are inaccessible to users outside the restricted region.
  const blockedIndicators = [
    "access denied",
    "forbidden",
    "geo restriction",
    "not available in your country",
    "service unavailable in your location",
    "blocked",
    "cloudflare challenge",
    "cloudflare verification",
    "verify you are human",
    "attention required",
    "temporarily unavailable",
    "restricted access",
  ];

  const pageContent = [
    crawl.title || "",
    crawl.description || "",
    crawl.homepageText || "",
  ].join(" ").toLowerCase();

  const isBlockedSite = blockedIndicators.some(indicator =>
    pageContent.includes(indicator)
  );

  // Flag geo-restricted/blocked sites but keep them — they may still be valid
  // citation directories (e.g. manta.com, angi.com) that are simply inaccessible
  // from the current region. A small citationScore penalty is applied later.
  let requiresVpn = false;
  if (isBlockedSite) {
    requiresVpn = true;
    logger.info(`[Pipeline] Site may require VPN or be geo-restricted: ${discoveredUrl}`);
  }

  // ── Step 3: Free listing detection (already in CrawlResult) ───────────────
  const canSubmitListing = crawl.canSubmitListing;
  const freeListing = crawl.freeListing ?? false;
  const submissionUrl = crawl.submissionUrl || null;

  if (freeListing) {
    logger.info(
      `  Free listing detected — signals: [${crawl.detectedKeywords.join(", ")}]`
    );
  } else {
    logger.info(`  No free listing signals detected`);
  }

  // ── Stage 5: Self-Submission Directory Filter ──────────────────────────────

  const domain = new URL(discoveredUrl).hostname.toLowerCase();
  const urlLower = discoveredUrl.toLowerCase();
  const titleLower = (crawl.title || discoveredTitle).toLowerCase();

  const excludedDomains = [
    "thryv.com",
    "justduckydigital.com",
    "thm2g.com",
    "truwayz.com",
    "citationforge.com",
    "iimskills.com",
    "saertechnologies.com",
    "tendtoread.com",
    "springssmallbusinessmarketing.com",
  ];

  // Skip known excluded domains before any scoring
  if (excludedDomains.some(d => domain.includes(d))) {
    logger.info(`Skipping recommendation site: ${domain}`);
    return null;
  }

  const positiveSignalList = [
    "add business", "submit listing", "submit business", "claim listing", "claim business",
    "add company", "create profile", "register business", "register your business", "join directory",
    "add listing", "list your business", "business owner", "for business owners", "business profile",
    "directory listing", "business directory", "advertise your business", "get listed", "business signup",
    "create business account", "add your business", "business registration", "submit company", "claim your profile",
    "company profile", "local business listing", "create listing", "add place", "claim this business"
  ];

  const submissionPatterns = [
    "add-business", "add-listing", "submit-listing", "claim-business", "claim-listing",
    "business-owners", "for-business", "for-professionals", "join", "register",
    "signup", "advertise", "get-listed"
  ];

  const serviceKeywords = [
    "citation service",
    "citation builder",
    "local seo",
    "seo agency",
    "marketing agency",
    "backlink service",
    "citation campaign",
    "citation management",
    "seo services",
    "digital marketing",
    "best citation sites",
    "top citation sites",
    "citation list",
    "directory submission services",
  ];

  // 1. Build signalText first — used by both directoryScore and downstream checks
  const signalText = [
    crawl.title || discoveredTitle,
    crawl.description || "",
    crawl.homepageText || "",
    (crawl.links || []).join(" "),
    discoveredUrl,
  ].join(" ").toLowerCase();

  // 2. Calculate directoryScore BEFORE agencyScore (agencyScore references it)
  const directorySignals = [
    "business directory",
    "directory listing",
    "add business",
    "submit listing",
    "claim listing",
    "claim business",
    "business profile",
    "company profile",
    "get listed",
    "join directory",
    "list your business",
    "add company",
    "register business",
  ];

  const urlSignals = [
    "/business", "/businesses", "/directory", "/directories",
    "/listing", "/listings", "/companies", "/company",
    "/profile", "/profiles", "/category", "/categories",
  ];

  let directoryScore = 0;
  directorySignals.forEach(signal => { if (signalText.includes(signal)) directoryScore += 5; });
  urlSignals.forEach(signal => { if (urlLower.includes(signal)) directoryScore += 3; });
  if (domain.includes("directory")) directoryScore += 10;
  if (domain.includes("listing"))   directoryScore += 10;
  if (domain.includes("business"))  directoryScore += 5;

  // 3. Calculate agencyScore AFTER directoryScore is available
  const agencyIndicators = [
    "marketing",
    "seo",
    "digital agency",
    "advertising",
    "lead generation",
    "web design",
    "branding",
    "consulting",
    "business growth",
    "local seo",
  ];

  const pageText = [
    titleLower,
    crawl.description?.toLowerCase() || "",
    crawl.homepageText?.toLowerCase().slice(0, 5000) || "",
  ].join(" ");

  let agencyScore = 0;
  agencyIndicators.forEach(kw => { if (pageText.includes(kw)) agencyScore += 3; });

  // 4. Evaluate isAgency only after both scores are available
  const isAgency = agencyScore >= 10 && directoryScore < 5;
  if (isAgency) {
    logger.info(`Skipping agency site: ${domain}`);
    return null;
  }

  // 5. Reject non-directory sites
  const looksLikeDirectory = directorySignals.some(x => signalText.includes(x));
  if (!looksLikeDirectory) {
    logger.info(`Skipping non-directory site: ${domain}`);
    return null;
  }

  // 6. Skip article/listicle pages
  const articleIndicators = [
    "best citation sites",
    "top citation sites",
    "citation sites list",
    "directory list",
    "local citation sites",
    "citation websites",
    "business directories list",
    "top business directories",
  ];
  if (articleIndicators.some(x => titleLower.includes(x))) {
    logger.info(`Skipping article page: ${titleLower}`);
    return null;
  }

  const hasPositiveSignals = positiveSignalList.some(s => signalText.includes(s));
  const hasSubmissionLink = (crawl.links || []).some(link =>
    submissionPatterns.some(pattern => link.toLowerCase().includes(pattern))
  );

  const isAgencyOrService = serviceKeywords.some(kw => signalText.includes(kw));

  const isGuideOrArticle =
    urlLower.includes("/blog/") ||
    urlLower.includes("/article/") ||
    urlLower.includes("/articles/") ||
    urlLower.includes("/news/") ||
    urlLower.includes("/guides/") ||
    urlLower.includes("/resources/") ||
    urlLower.includes("/top-") ||
    urlLower.includes("/best-") ||
    urlLower.includes("/list-") ||
    urlLower.includes("/citation-sites");

  if (isAgencyOrService) {
    logger.info(`Skipping agency/service site`);
    return null;
  }

  if (isGuideOrArticle) {
    logger.info(`Skipping guide/article`);
    return null;
  }

  let supportsSelfSubmission = false;
  let matchReason = "Not classified";

  if (hasPositiveSignals || hasSubmissionLink) {
    supportsSelfSubmission = true;
    matchReason = hasSubmissionLink
      ? "Submission link detected"
      : "Self-submission signals detected";
  } else {
    matchReason = "No self-submission signals";
  }

  const aggregatorDomains = [
    "yelp.com",
    "facebook.com",
    "bing.com",
    "apple.com",
    "bbb.org",
    "yellowpages.com",
    "foursquare.com",
    "mapquest.com",
  ];

  const isAggregator = aggregatorDomains.some(d => domain.includes(d));

  let citationScore = 0;
  if (hasPositiveSignals)    citationScore += 5;
  if (hasSubmissionLink)     citationScore += 5;
  if (submissionUrl)         citationScore += 10;
  if (supportsSelfSubmission) citationScore += 10;
  if (domain.includes("directory")) citationScore += 3;
  if (domain.includes("listing"))   citationScore += 3;
  if (domain.includes("business"))  citationScore += 2;
  if (isAggregator)          citationScore += 8;
  // Penalise sites that appear geo-restricted — still valid, just harder to access
  if (requiresVpn) {
    citationScore -= 5;
    matchReason = "Directory accessible via VPN";
  }

  console.log({
    url: discoveredUrl,
    positive: hasPositiveSignals,
    submissionLink: hasSubmissionLink,
    agency: isAgencyOrService,
    guide: isGuideOrArticle,
    reason: matchReason
  });

  console.log(
    `[Stage5] ${discoveredUrl} | positive=${hasPositiveSignals} | agency=${isAgencyOrService} | guide=${isGuideOrArticle} | result=${supportsSelfSubmission}`
  );

  // ── Step 4: Classify industry ──────────────────────────────────────────────
  const classificationText = [
    crawl.title       || discoveredTitle,
    crawl.description || "",
    crawl.homepageText || "",
    discoveredUrl,
  ].join(" ");

  logger.info(`  Classifying industry…`);
  const classification = await classifyIndustry(classificationText);
  console.log("Classified website:", discoveredUrl, "->", classification.industry);
  logger.info(
    `  Industry: "${classification.industry}" ` +
    `(${classification.confidence} confidence, ` +
    `${classification.matchedKeywords.length} keyword matches)`
  );

  // ── Step 5: Get Moz Metrics ──────────────────────────────────────────────
  let domainAuthority = 0;
  let spamScore = 0;

  try {
    logger.info(`  Fetching Moz metrics…`);
    const mozData = await getMozMetrics(discoveredUrl);
    domainAuthority = mozData.domainAuthority;
    spamScore = mozData.spamScore;
    logger.info(`  Moz metrics retrieved — DA: ${domainAuthority}, Spam: ${spamScore}`);
  } catch (err) {
    logger.warn(
      `  Moz metrics failed — defaulting to 0 (${err instanceof Error ? err.message : "unknown error"})`
    );
  }

  const daCategoryStr   = categorizeDa(domainAuthority);
  logger.info(`  DA: ${domainAuthority} → category: ${daCategoryStr}`);

  // ── Step 6: Save to database ───────────────────────────────────────────────
  const websiteInput = {
    name:            crawl.title || discoveredTitle,
    url:             crawl.url   || discoveredUrl,
    description:     crawl.description,
    domainAuthority,
    spamScore,
    estimatedTraffic: Math.floor(Math.random() * 5000), // Placeholder for traffic API
    contactEmail:    crawl.email,
    socialLinks:     crawl.socials as any,
    freeListing,
    industry:        classification.industry,
    daCategory:      daCategoryStr as DaCategory,
    active:          true,
    freeOrPaid:      crawl.freeOrPaid,
    canSubmitListing,
    submissionUrl,
    type,
    rankPosition,
    sourceProvider
  };

  let savedId = `pending-${index}`;

  if (!dryRun) {
    try {
      console.log("Saving website:", websiteInput.url);
      const saved = await saveDiscoveredWebsite(websiteInput);
      savedId = saved.id;
      console.log("Saved website:", savedId);
    } catch (err) {
      logger.warn(
        `  DB save skipped — ${err instanceof Error ? err.message : "unknown error"}`
      );
    }
  } else {
    logger.info(`  Dry run — skipping database save`);
  }

  return {
    id:             savedId,
    name:           websiteInput.name,
    url:            websiteInput.url,
    description:    websiteInput.description || null,
    domainAuthority,
    spamScore,
    freeListing:    websiteInput.freeListing,
    freeOrPaid:     websiteInput.freeOrPaid,
    industry:       classification.industry,
    daCategory:     daCategoryStr,
    estimatedTraffic: websiteInput.estimatedTraffic,
    contactEmail:    websiteInput.contactEmail || null,
    canSubmitListing,
    submissionUrl,
    socialLinks:     websiteInput.socialLinks,
    active:         true,
    type,
    rankPosition,
    sourceProvider,
    category: classification.industry,
    supportsSelfSubmission,
    matchReason,
    citationScore,
    isAggregator,
    requiresVpn,
  };
}

export async function runDiscoveryPipeline(
  keyword: string,
  options: PipelineOptions = {}
): Promise<PipelineReport> {
  const { dryRun = false } = options;
  const startedAt = new Date();

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Search started — keyword: "${keyword}"`);
  if (dryRun) logger.info(`Dry run — database writes disabled`);
  logger.info(`══════════════════════════════════════════`);
  // ── Step 1: Discover website URLs ──────────────────────────────────────────
  logger.info(`Step 1 — Discovering websites…`);

  console.log(`Search started (Step 1): "${keyword}"`);
  let discovery;
  try {
    discovery = await discoverWebsites(keyword, undefined);

    // Pre-crawl ranking: directoryScore DESC, search rank ASC
    discovery.results = discovery.results.map((r, i) => ({
      ...r,
      directoryScore: scoreDirectoryCandidate(r.url),
      rankPosition: i + 1
    })).sort((a, b) => {
      if ((b.directoryScore || 0) !== (a.directoryScore || 0)) {
        return (b.directoryScore || 0) - (a.directoryScore || 0);
      }
      return (a.rankPosition || 0) - (b.rankPosition || 0);
    });

    console.log("Top directory candidates");
    console.table(
      discovery.results.slice(0, 50).map(x => ({
        url: x.url,
        score: x.directoryScore
      }))
    );

    logger.info(`Selected provider: ${discovery.provider}`);
    logger.info(`Search queries: ${discovery.queries.join(" | ")}`);
    console.log(`URLs discovered: ${discovery.results.length}`);
    console.log(`URLs discovered: ${discovery.results.length}`);
    console.log(`Discovered websites: ${discovery.results.length} using ${discovery.provider} provider`);
    console.log(`URLs discovered: ${discovery.results.map((item) => item.url).join(" | ")}`);
    logger.info(`Websites discovered — ${discovery.results.length} URL(s)`);
  } catch (err) {
    logger.error(
      `Step 1 failed — ${err instanceof Error ? err.message : "unknown error"}`
    );
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      "none",
      isFallback:  false,
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }

  if (discovery.results.length === 0) {
    logger.warn(`No URLs discovered — pipeline complete with zero results`);
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      discovery.provider,
      isFallback:  discovery.provider === "mock" || discovery.provider === "directory-fallback",
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }
  
  console.log("Discovered websites:", discovery.results.length);

  // ── Steps 2–6: Process URLs with throttled concurrency mapping ──────────────────
  logger.info(
    `Steps 2–6 — Processing ${discovery.results.length} URL(s) with concurrency limit 3 and staggering…`
  );

  let rawResults: (PipelineResult | null)[] = [];

  try {
    // Process ALL results with a concurrency limit of 3 (as per previous audit's log)
    rawResults = await mapConcurrent(discovery.results, 3, async (item, i) => {
      console.log(`URLs crawled: ${item.url}`);
      logger.info(`Starting processUrl for ${item.url} (item ${i + 1}/${discovery.results.length})`);
      return processUrl(
        item.url, 
        item.title, 
        i + 1, 
        discovery.results.length, 
        dryRun, 
        item.rankPosition, 
        item.sourceProvider,
        item.type
      );
    });
  } finally {
    // ── Cleanup: close the shared Playwright browser ───────────────────────────
    await closeBrowser();
    logger.info(`Browser closed`);
  }

  const successful = rawResults.filter((r) => r !== null);
  console.log(`URLs after filtering: ${successful.length}`);
  console.log(`URLs removed: ${discovery.results.length - successful.length}`);

  const processedCount = rawResults.filter(r => r !== null).length;
  console.log(`URLs after classification: ${processedCount}`);

  // The filtering for self-submission, agencies, and blogs is now done in processUrl.
  // Here we just sort the successful results.
  successful.sort((a, b) => {
    // 1. Industry-specific directories
    const aIndustry =
      a.matchReason === "Industry tag" ||
      a.category === keyword;

    const bIndustry =
      b.matchReason === "Industry tag" ||
      b.category === keyword;

    if (aIndustry && !bIndustry) return -1;
    if (!aIndustry && bIndustry) return 1;

    // 2. Aggregators
    const aAggregator = a.isAggregator;
    const bAggregator = b.isAggregator;

    if (aAggregator && !bAggregator) return -1;
    if (!aAggregator && bAggregator) return 1;

    // 3. Citation score
    if (b.citationScore !== a.citationScore) {
      return b.citationScore - a.citationScore;
    }

    // 4. Direct submission URL
    if (a.submissionUrl && !b.submissionUrl) return -1;
    if (!a.submissionUrl && b.submissionUrl) return 1;

    // 5. DA tie-breaker
    return b.domainAuthority - a.domainAuthority;
  });

  // Audit Log: Classify top 20 passing URLs
  console.log("=== Ranking Breakdown ===");

  successful.slice(0, 20).forEach((r, i) => {
    console.log({
      rank: i + 1,
      url: r.url,
      industry: r.category,
      citationScore: r.citationScore,
      aggregator: r.isAggregator,
      submissionUrl: !!r.submissionUrl,
      da: r.domainAuthority,
      reason: r.matchReason
    });
  });

  logger.info(`Crawled websites — ${successful.length}/${discovery.results.length}`);
  
  const results: PipelineResult[] = successful;
  let saved  = 0;
  let failed = 0;

  results.forEach(result => {
    if (!result.id.startsWith("pending-")) {
      saved++;
    }
  });

  failed = discovery.results.length - results.length; // This needs to be re-evaluated based on actual failures

  const completedAt = new Date();
  const durationMs  = completedAt.getTime() - startedAt.getTime();

  // Diagnostics calculations
  const providerSelected = discovery.provider;
  const urlsDiscoveredCount = discovery.results.length + (discovery.filteredCount || 0);
  const urlsFilteredCount = discovery.filteredCount || 0;
  const urlsCrawledCount = discovery.results.length;
  const urlsSavedCount = saved;
  const crawlSuccessRatePercent = urlsCrawledCount > 0 ? Math.round((successful.length / urlsCrawledCount) * 100) : 0;
  const saveSuccessRatePercent = successful.length > 0 ? Math.round((saved / successful.length) * 100) : 0;

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Results returned — ${results.length} websites`);
  logger.info(`Pipeline complete in ${durationMs}ms`);
  logger.info(`══════════════════════════════════════════`);

  return {
    keyword,
    discovered:  discovery.results.length,
    processed:   results.length,
    saved,
    failed,
    results,
    source:      discovery.provider,
    isFallback:  discovery.provider === "mock",
    startedAt:   formatDateSafe(startedAt),
    completedAt: formatDateSafe(completedAt),
    diagnostics: {
      providerSelected,
      urlsDiscoveredCount,
      urlsFilteredCount,
      urlsCrawledCount,
      urlsSavedCount,
      crawlSuccessRatePercent,
      saveSuccessRatePercent,
      discoveredBlogs: discovery.diagnostics?.blogs.length,
      discoveredDirectories: discovery.diagnostics?.directories.length,
      discoveredBusinessSites: discovery.diagnostics?.businessSites.length,
    }
  };
}
