// services/discoveryPipeline.ts
//
// Orchestrates the complete website discovery process end-to-end.
//
// Pipeline:
//   runDiscoveryPipeline(keyword)
//     ├── Step 1: discoverWebsites()     — find URLs via mock/Google/Bing
//     ├── Step 2: crawlWebsite()         — visit each URL with Playwright
//     ├── Step 3: (from crawl result)    — detect free listing signals
//     ├── Step 4: classifyIndustry()     — keyword or OpenAI classification
//     ├── Step 5: getMozMetrics()        — fetch real DA and spam scores
//     ├── Step 6: categorizeDa()         — map DA number → Low/Average/Excellent
//     ├── Step 6: createWebsite()        — persist to database (skipped if DB down)
//     └── Return: PipelineReport

import { discoverWebsites }           from "@/services/discoveryService";
import { crawlWebsite, closeBrowser } from "@/services/crawlerService";
import { classifyIndustry }           from "@/services/industryClassifier";
import { saveDiscoveredWebsite }      from "@/services/websiteService";
import { getMozMetrics }              from "@/services/mozService";
import { DaCategory }                 from "@prisma/client";
import { mapConcurrent }              from "@/lib/concurrency"; // Import centralized mapConcurrent
import { logger }                     from "./logger";
import { formatDateSafe }             from "./dateUtils";

// ─── Types ────────────────────────────────────────────────────────────────────

/** Shape returned by the pipeline — matches the Website UI interface exactly. */
export interface PipelineResult {
  id: string;
  name: string;
  url: string;
  description: string | null;
  domainAuthority: number;
  spamScore: number;
  freeListing: boolean;
  industry: string;
  daCategory: "Low" | "Average" | "Excellent";
  estimatedTraffic: number;
  contactEmail: string | null;
  socialLinks: Record<string, string> | null;
  active: boolean;
  freeOrPaid: string;
  canSubmitListing: boolean;
  submissionUrl: string | null;
  type?: "listingOpportunity";
  rankPosition?: number;
  sourceProvider?: string;
  hasAddBusiness: boolean;
  hasSubmitListing: boolean;
  hasClaimListing: boolean;
  hasCreateProfile: boolean;
  listingConfidence: number;
  listingCapable: boolean;
  listingOpportunityScore: number;
  positiveSignalsFound: string[];
  negativeSignalsFound: string[];
  isRealDirectory: boolean;
  filterReason: string | null;
  directoryQualityScore: number;
  sortReason: string;
}

export interface PipelineOptions {
  /**
   * When true, skips the database save step (Step 6).
   * Useful for dry-run / preview mode without persisting anything.
   * Default: false
   */
  dryRun?: boolean;
}

export interface PipelineReport {
  keyword: string;
  /** Total URLs returned by the discovery step. */
  discovered: number;
  /** URLs successfully processed through the full pipeline. */
  processed: number;
  /** URLs successfully saved to the database. */
  saved: number;
  /** URLs that failed processing and were skipped. */
  failed: number;
  results: PipelineResult[];
  /** Discovery source provider name. */
  source: string;
  /** True if results were generated by a mock or fallback provider. */
  isFallback: boolean;
  startedAt: string;
  completedAt: string;
  diagnostics?: {
    providerSelected: string;
    urlsDiscoveredCount: number;
    urlsFilteredCount: number;
    urlsCrawledCount: number;
    urlsSavedCount: number;
    crawlSuccessRatePercent: number;
    saveSuccessRatePercent: number;
    discoveredBlogs?: number;
    discoveredDirectories?: number;
    discoveredBusinessSites?: number;
  };
}

// ─── DA categorisation ────────────────────────────────────────────────────────

/**
 * Maps a numeric Domain Authority score to a category label.
 *
 * Ranges:
 *   0–20   → Low
 *   21–50  → Average
 *   51–100 → Excellent
 */
export function categorizeDa(da: number): "Low" | "Average" | "Excellent" {
  if (da <= 20) return "Low";
  if (da <= 50) return "Average";
  return "Excellent";
}

// ─── Per-URL processor ────────────────────────────────────────────────────────

/**
 * Runs steps 2–6 for a single discovered URL.
 * Returns null if the URL itself is invalid, fails to load, or has empty content.
 */
async function processUrl(
  discoveredUrl: string,
  discoveredTitle: string,
  index: number,
  total: number,
  dryRun: boolean,
  rankPosition?: number,
  sourceProvider?: string,
  type?: "listingOpportunity"
): Promise<PipelineResult | null> {
  logger.info(`[Pipeline] [${index}/${total}] ${discoveredUrl}`);

  // ── Step 2: Crawl the website with Playwright ──────────────────────────────
  logger.info(`  Websites crawled — ${discoveredUrl}…`);
  const crawl = await crawlWebsite(discoveredUrl);

  if (crawl.error) {
    logger.warn(`  Crawl failed (${crawl.error}) — skipping`);
    return null;
  }

  if (!crawl.homepageText || !crawl.homepageText.trim()) {
    logger.warn(`  Empty content returned — skipping`);
    return null;
  }

  logger.info(`  Crawled — title: "${crawl.title}"`);

  // ── Step 3: Free listing detection (already in CrawlResult) ───────────────
  const canSubmitListing = crawl.canSubmitListing;
  const freeListing = crawl.freeListing ?? false;
  const submissionUrl = crawl.submissionUrl || null;

  const detected = crawl.detectedKeywords || [];
  const hasAddBusiness = detected.some(k => k === "Add Business" || k === "Add Company");
  const hasSubmitListing = detected.some(k => k === "Submit Listing" || k === "Submit Business");
  const hasClaimListing = detected.some(k => k === "Claim Business");
  const hasCreateProfile = detected.some(k => ["Create Profile", "Create Business Profile", "Business Signup", "Register Business", "Create Listing"].includes(k));

  // Confidence calculation: 40% for direct URL, 15% for each unique action type detected
  let confScore = 0;
  if (crawl.submissionUrl) confScore += 40;
  if (hasAddBusiness) confScore += 15;
  if (hasSubmitListing) confScore += 15;
  if (hasClaimListing) confScore += 15;
  if (hasCreateProfile) confScore += 15;
  const listingConfidence = Math.min(100, confScore);

  // ── Step 3.5: Listing Opportunity Detection (Stage 2) ─────────────────────
  const signalText = [
    crawl.title       || discoveredTitle,
    crawl.description || "",
    crawl.homepageText || "",
    (crawl.links || []).join(" "),
    discoveredUrl,
  ].join(" ").toLowerCase();

  const positiveSignalList = [
    "add business", "submit listing", "submit business", "claim listing", "claim business",
    "add company", "create profile", "register business", "get listed", "join directory", "add listing"
  ];
  const negativeSignalList = [
    "blog", "guide", "how to", "tips", "best citation sites", "top citation sites",
    "seo guide", "marketing guide", "article"
  ];

  const positiveSignalsFound = positiveSignalList.filter(s => signalText.includes(s));
  const negativeSignalsFound = negativeSignalList.filter(s => signalText.includes(s));
  const listingOpportunityScore = (positiveSignalsFound.length * 25) - (negativeSignalsFound.length * 15);
  const listingCapable = positiveSignalsFound.length > 0;

  // ── Step 3.6: Directory Verification (Stage 3) ────────────────────────────
  const directoryKeywords = ["business directory", "directory category", "directory listings", "business listings", "pages"];
  const hasDirectorySignals = directoryKeywords.some(kw => signalText.includes(kw));
  
  // Task 2: Mark TRUE if submission signals or directory patterns exist
  let isRealDirectory = hasAddBusiness || hasSubmitListing || hasClaimListing || hasCreateProfile || hasDirectorySignals;

  // Task 3: Mark FALSE if informational content patterns are found
  const informationalKeywords = [
    "blog", "seo guide", "citation guide", "top citation sites", 
    "best citation sites", "marketing article", "resource page", "news article", "tips"
  ];
  const hasInformationalSignals = informationalKeywords.some(kw => signalText.includes(kw));
  
  if (hasInformationalSignals) {
    isRealDirectory = false;
  }

  const filterReason = hasAddBusiness || hasSubmitListing || hasClaimListing || hasCreateProfile
    ? "Direct submission signals"
    : isRealDirectory 
      ? "Identified as directory structure"
      : "Informational or low-intent content";

  // ── Step 3.7: Directory Quality Ranking (Stage 4) ─────────────────────────
  let directoryQualityScore = 0;
  if (hasAddBusiness) directoryQualityScore += 100;
  if (hasSubmitListing) directoryQualityScore += 80;
  if (hasClaimListing) directoryQualityScore += 80;
  if (hasCreateProfile) directoryQualityScore += 60;

  const qualityKeywords = ["directory", "listing", "business-directory", "yellowpages", "hotfrog", "manta", "brownbook", "fyple"];
  const domainName = new URL(discoveredUrl).hostname.toLowerCase();
  if (qualityKeywords.some(kw => domainName.includes(kw))) {
    directoryQualityScore += 40;
  }

  if (freeListing) {
    directoryQualityScore += 20;
  }

  const negativeQualityKeywords = ["blog", "guide", "article", "seo resource"];
  if (negativeQualityKeywords.some(kw => signalText.includes(kw))) {
    directoryQualityScore -= 50;
  }

  const sortReason = directoryQualityScore >= 150 
    ? "Verified submission platform" 
    : directoryQualityScore >= 100 
      ? "Strong directory signals" 
      : directoryQualityScore > 40 
        ? "Potential directory" 
        : "General content";

  if (freeListing) {
    logger.info(
      `  Free listing detected — signals: [${crawl.detectedKeywords.join(", ")}]`
    );
  } else {
    logger.info(`  No free listing signals detected`);
  }

  // ── Step 4: Classify industry ──────────────────────────────────────────────
  const classificationText = [
    crawl.title       || discoveredTitle,
    crawl.description || "",
    crawl.homepageText || "",
    discoveredUrl,
  ].join(" ");

  logger.info(`  Classifying industry…`);
  const classification = await classifyIndustry(classificationText);
  console.log("Classified website:", discoveredUrl, "->", classification.industry);
  logger.info(
    `  Industry: "${classification.industry}" ` +
    `(${classification.confidence} confidence, ` +
    `${classification.matchedKeywords.length} keyword matches)`
  );

  // ── Step 5: Get Moz Metrics ──────────────────────────────────────────────
  let domainAuthority = 0;
  let spamScore = 0;

  try {
    logger.info(`  Fetching Moz metrics…`);
    const mozData = await getMozMetrics(discoveredUrl);
    domainAuthority = mozData.domainAuthority;
    spamScore = mozData.spamScore;
    logger.info(`  Moz metrics retrieved — DA: ${domainAuthority}, Spam: ${spamScore}`);
  } catch (err) {
    logger.warn(
      `  Moz metrics failed — defaulting to 0 (${err instanceof Error ? err.message : "unknown error"})`
    );
  }

  const daCategoryStr   = categorizeDa(domainAuthority);
  logger.info(`  DA: ${domainAuthority} → category: ${daCategoryStr}`);

  // ── Step 6: Save to database ───────────────────────────────────────────────
  const websiteInput = {
    name:            crawl.title || discoveredTitle,
    url:             crawl.url   || discoveredUrl,
    description:     crawl.description,
    domainAuthority,
    spamScore,
    estimatedTraffic: Math.floor(Math.random() * 5000), // Placeholder for traffic API
    contactEmail:    crawl.email,
    socialLinks:     crawl.socials as any,
    freeListing,
    industry:        classification.industry,
    daCategory:      daCategoryStr as DaCategory,
    active:          true,
    freeOrPaid:      crawl.freeOrPaid,
    canSubmitListing,
    submissionUrl,
    type,
    rankPosition,
    sourceProvider
  };

  let savedId = `pending-${index}`;

  if (!dryRun) {
    try {
      console.log("Saving website:", websiteInput.url);
      const saved = await saveDiscoveredWebsite(websiteInput);
      savedId = saved.id;
      console.log("Saved website:", savedId);
    } catch (err) {
      logger.warn(
        `  DB save skipped — ${err instanceof Error ? err.message : "unknown error"}`
      );
    }
  } else {
    logger.info(`  Dry run — skipping database save`);
  }

  return {
    id:             savedId,
    name:           websiteInput.name,
    url:            websiteInput.url,
    description:    websiteInput.description || null,
    domainAuthority,
    spamScore,
    freeListing:    websiteInput.freeListing,
    freeOrPaid:     websiteInput.freeOrPaid,
    industry:       classification.industry,
    daCategory:     daCategoryStr,
    estimatedTraffic: websiteInput.estimatedTraffic,
    contactEmail:    websiteInput.contactEmail || null,
    canSubmitListing,
    submissionUrl,
    socialLinks:     websiteInput.socialLinks,
    active:         true,
    type,
    rankPosition,
    sourceProvider,
    hasAddBusiness,
    hasSubmitListing,
    hasClaimListing,
    hasCreateProfile,
    listingConfidence,
    listingCapable,
    listingOpportunityScore,
    positiveSignalsFound,
    negativeSignalsFound,
    isRealDirectory,
    filterReason,
    directoryQualityScore,
    sortReason
  };
}

export async function runDiscoveryPipeline(
  keyword: string,
  options: PipelineOptions = {}
): Promise<PipelineReport> {
  const { dryRun = false } = options;
  const startedAt = new Date();

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Search started — keyword: "${keyword}"`);
  if (dryRun) logger.info(`Dry run — database writes disabled`);
  logger.info(`══════════════════════════════════════════`);
  // ── Step 1: Discover website URLs ──────────────────────────────────────────
  logger.info(`Step 1 — Discovering websites…`);

  console.log(`Search started (Step 1): "${keyword}"`);
  let discovery;
  try {
    discovery = await discoverWebsites(keyword, undefined);
    logger.info(`Selected provider: ${discovery.provider}`);
    logger.info(`Search queries: ${discovery.queries.join(" | ")}`);
    console.log(`URLs discovered: ${discovery.results.length}`);
    console.log(`Discovered websites: ${discovery.results.length} using ${discovery.provider} provider`);
    console.log(`URLs discovered: ${discovery.results.map((item) => item.url).join(" | ")}`);
    logger.info(`Websites discovered — ${discovery.results.length} URL(s)`);
  } catch (err) {
    logger.error(
      `Step 1 failed — ${err instanceof Error ? err.message : "unknown error"}`
    );
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      "none",
      isFallback:  false,
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }

  if (discovery.results.length === 0) {
    logger.warn(`No URLs discovered — pipeline complete with zero results`);
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      discovery.provider,
      isFallback:  discovery.provider === "mock" || discovery.provider === "directory-fallback",
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }
  console.log("Discovered websites:", discovery.results.length);

  // ── Steps 2–6: Process URLs with throttled concurrency mapping ──────────────────
  logger.info(
    `Steps 2–6 — Processing ${discovery.results.length} URL(s) with concurrency limit 3 and staggering…`
  );

  let rawResults: (PipelineResult | null)[] = [];

  try {
    // Process ALL results with a concurrency limit of 3 (as per previous audit's log)
    rawResults = await mapConcurrent(discovery.results, 3, async (item, i) => {
      console.log(`URLs crawled: ${item.url}`);
      logger.info(`Starting processUrl for ${item.url} (item ${i + 1}/${discovery.results.length})`);
      return processUrl(
        item.url, 
        item.title, 
        i + 1, 
        discovery.results.length, 
        dryRun, 
        item.rankPosition, 
        item.sourceProvider,
        item.type
      );
    });
  } finally {
    // ── Cleanup: close the shared Playwright browser ───────────────────────────
    await closeBrowser();
    logger.info(`Browser closed`);
  }

  const successful = rawResults.filter(r => r !== null);
  console.log(`URLs after crawl: ${successful.length}`);

  const processedCount = rawResults.filter(r => r !== null).length;
  console.log(`URLs after classification: ${processedCount}`);

  // ── Step 7: Apply Directory-Only Filtering (Stage 3) ───────────────────────
  const beforeFilterCount = successful.length;
  
  const filteredResults = successful.filter(r => {
    const domain = new URL(r.url).hostname;
    // Task 5: Keep if direct submission signals exist
    const overrideKeep = r.hasAddBusiness || r.hasSubmitListing || r.hasClaimListing || r.hasCreateProfile;
    
    // Task 4: Exclude if score is non-positive and not a directory
    const shouldExclude = !overrideKeep && (r.listingOpportunityScore <= 0 && !r.isRealDirectory);

    if (shouldExclude) {
      console.log(`REMOVING: ${domain.padEnd(30)} | Reason: ${r.filterReason}`);
      return false;
    }

    console.log(`KEEPING:  ${domain.padEnd(30)} | Reason: ${r.filterReason}`);
    return true;
  });

  const afterFilterCount = filteredResults.length;

  // Rank results by quality score, opportunity score, and DA (Stage 4)
  filteredResults.sort((a, b) => {
    if (b.directoryQualityScore !== a.directoryQualityScore) {
      return b.directoryQualityScore - a.directoryQualityScore;
    }
    if (b.listingOpportunityScore !== a.listingOpportunityScore) {
      return b.listingOpportunityScore - a.listingOpportunityScore;
    }
    return b.domainAuthority - a.domainAuthority;
  });

  logger.info(`Crawled websites — ${afterFilterCount}/${discovery.results.length}`);
  
  const results: PipelineResult[] = [];
  let saved  = 0;
  let failed = 0;

  filteredResults.forEach(result => {
    results.push(result);
    if (!result.id.startsWith("pending-")) {
      saved++;
    }
  });

  failed = discovery.results.length - results.length;

  const completedAt = new Date();
  const durationMs  = completedAt.getTime() - startedAt.getTime();

  // Diagnostics calculations
  const providerSelected = discovery.provider;
  const urlsDiscoveredCount = discovery.results.length + (discovery.filteredCount || 0);
  const urlsFilteredCount = discovery.filteredCount || 0;
  const urlsCrawledCount = discovery.results.length;
  const urlsSavedCount = saved;
  const crawlSuccessRatePercent = urlsCrawledCount > 0 ? Math.round((successful.length / urlsCrawledCount) * 100) : 0;
  const saveSuccessRatePercent = successful.length > 0 ? Math.round((saved / successful.length) * 100) : 0;

  console.log(`\n==================================================`);
  console.log(`[Pipeline Diagnostics]`);
  console.log(`- Provider Selected: ${providerSelected}`);
  console.log(`- URLs Discovered: ${urlsDiscoveredCount}`);
  console.log(`- URLs Filtered: ${urlsFilteredCount}`);
  console.log(`- URLs Crawled: ${urlsCrawledCount}`);
  console.log(`- URLs Saved: ${urlsSavedCount}`);
  console.log(`- Crawl Success Rate: ${crawlSuccessRatePercent}%`);
  console.log(`- Save Success Rate: ${saveSuccessRatePercent}%`);
  console.log(`==================================================\n`);

  // Stage 4 Audit Report
  console.log(`\n--- Stage 4 Listing Opportunity Ranking Audit (Top 20) ---`);
  console.log(`Before Filter: ${beforeFilterCount} | After Filter: ${afterFilterCount}`);
  console.log("-".repeat(120));
  console.log(`${"Name".padEnd(30)} | ${"Quality".padEnd(8)} | ${"Opp Score".padEnd(10)} | ${"DA".padEnd(4)} | ${"Sort Reason"}`);
  console.log("-".repeat(120));
  
  results.slice(0, 20).forEach(r => {
    console.log(
      `${r.name.slice(0, 30).padEnd(30)} | ` +
      `${String(r.directoryQualityScore).padEnd(8)} | ` +
      `${String(r.listingOpportunityScore).padEnd(10)} | ` +
      `${String(r.domainAuthority).padEnd(4)} | ` +
      `${r.sortReason}`
    );
  });
  console.log(`------------------------------------------------------------------------------------------------------------------------\n`);

  console.log(`\n--- Top 20 Ranked Domains ---`);
  results.slice(0, 20).forEach((r, i) => {
    const domain = new URL(r.url).hostname;
    console.log(`${i + 1}. ${domain} (Score: ${r.directoryQualityScore})`);
  });

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Results returned — ${results.length} websites`);
  logger.info(`Pipeline complete in ${durationMs}ms`);
  logger.info(`══════════════════════════════════════════`);

  return {
    keyword,
    discovered:  discovery.results.length,
    processed:   results.length,
    saved,
    failed,
    results,
    source:      discovery.provider,
    isFallback:  discovery.provider === "mock" || discovery.provider === "directory-fallback",
    startedAt:   formatDateSafe(startedAt),
    completedAt: formatDateSafe(completedAt),
    diagnostics: {
      providerSelected,
      urlsDiscoveredCount,
      urlsFilteredCount,
      urlsCrawledCount,
      urlsSavedCount,
      crawlSuccessRatePercent,
      saveSuccessRatePercent,
      discoveredBlogs: discovery.diagnostics?.blogs.length,
      discoveredDirectories: discovery.diagnostics?.directories.length,
      discoveredBusinessSites: discovery.diagnostics?.businessSites.length,
    }
  };
}
