// services/discoveryPipeline.ts
//
// Orchestrates the complete website discovery process end-to-end.
//
// Pipeline:
//   runDiscoveryPipeline(keyword)
//     ├── Step 1: discoverWebsites()     — find URLs via mock/Google/Bing
//     ├── Step 2: crawlWebsite()         — visit each URL with Playwright
//     ├── Step 3: (from crawl result)    — detect free listing signals
//     ├── Step 4: classifyIndustry()     — keyword or OpenAI classification
//     ├── Step 5: getMozMetrics()        — fetch real DA and spam scores
//     ├── Step 6: categorizeDa()         — map DA number → Low/Average/Excellent
//     ├── Step 6: createWebsite()        — persist to database (skipped if DB down)
//     └── Return: PipelineReport

import { discoverWebsites }           from "@/services/discoveryService";
import { crawlWebsite, closeBrowser } from "@/services/crawlerService";
import { classifyIndustry }           from "@/services/industryClassifier";
import { saveDiscoveredWebsite }      from "@/services/websiteService";
import { getMozMetrics }              from "@/services/mozService";
import { DaCategory }                 from "@prisma/client";
import { mapConcurrent }              from "@/lib/concurrency"; // Import centralized mapConcurrent
import { logger }                     from "./logger";
import { formatDateSafe }             from "./dateUtils";

// ─── Types ────────────────────────────────────────────────────────────────────

/** Shape returned by the pipeline — matches the Website UI interface exactly. */
export interface PipelineResult {
  id: string;
  name: string;
  url: string;
  description: string | null;
  domainAuthority: number;
  spamScore: number;
  freeListing: boolean;
  industry: string;
  daCategory: "Low" | "Average" | "Excellent";
  estimatedTraffic: number;
  contactEmail: string | null;
  socialLinks: Record<string, string> | null;
  active: boolean;
}

export interface PipelineOptions {
  /**
   * When true, skips the database save step (Step 6).
   * Useful for dry-run / preview mode without persisting anything.
   * Default: false
   */
  dryRun?: boolean;
}

export interface PipelineReport {
  keyword: string;
  /** Total URLs returned by the discovery step. */
  discovered: number;
  /** URLs successfully processed through the full pipeline. */
  processed: number;
  /** URLs successfully saved to the database. */
  saved: number;
  /** URLs that failed processing and were skipped. */
  failed: number;
  results: PipelineResult[];
  /** Discovery source provider name. */
  source: string;
  /** True if results were generated by a mock or fallback provider. */
  isFallback: boolean;
  startedAt: string;
  completedAt: string;
  diagnostics?: {
    providerSelected: string;
    urlsDiscoveredCount: number;
    urlsFilteredCount: number;
    urlsCrawledCount: number;
    urlsSavedCount: number;
    crawlSuccessRatePercent: number;
    saveSuccessRatePercent: number;
  };
}

// ─── DA categorisation ────────────────────────────────────────────────────────

/**
 * Maps a numeric Domain Authority score to a category label.
 *
 * Ranges:
 *   0–20   → Low
 *   21–50  → Average
 *   51–100 → Excellent
 */
export function categorizeDa(da: number): "Low" | "Average" | "Excellent" {
  if (da <= 20) return "Low";
  if (da <= 50) return "Average";
  return "Excellent";
}

// ─── Per-URL processor ────────────────────────────────────────────────────────

/**
 * Runs steps 2–6 for a single discovered URL.
 * Returns null if the URL itself is invalid, fails to load, or has empty content.
 */
async function processUrl(
  discoveredUrl: string,
  discoveredTitle: string,
  index: number,
  total: number,
  dryRun: boolean
): Promise<PipelineResult | null> {
  logger.info(`[Pipeline] [${index}/${total}] ${discoveredUrl}`);

  // ── Step 2: Crawl the website with Playwright ──────────────────────────────
  logger.info(`  Websites crawled — ${discoveredUrl}…`);
  const crawl = await crawlWebsite(discoveredUrl);

  if (crawl.error) {
    logger.warn(`  Crawl failed (${crawl.error}) — skipping`);
    return null;
  }

  if (!crawl.homepageText || !crawl.homepageText.trim()) {
    logger.warn(`  Empty content returned — skipping`);
    return null;
  }

  logger.info(`  Crawled — title: "${crawl.title}"`);

  // ── Step 3: Free listing detection (already in CrawlResult) ───────────────
  const freeListing = crawl.freeListing;
  if (freeListing) {
    logger.info(
      `  Free listing detected — signals: [${crawl.detectedKeywords.join(", ")}]`
    );
  } else {
    logger.info(`  No free listing signals detected`);
  }

  // ── Step 4: Classify industry ──────────────────────────────────────────────
  const classificationText = [
    crawl.title       || discoveredTitle,
    crawl.description || "",
    crawl.homepageText || "",
    discoveredUrl,
  ].join(" ");

  logger.info(`  Classifying industry…`);
  const classification = await classifyIndustry(classificationText);
  console.log("Classified website:", discoveredUrl, "->", classification.industry);
  logger.info(
    `  Industry: "${classification.industry}" ` +
    `(${classification.confidence} confidence, ` +
    `${classification.matchedKeywords.length} keyword matches)`
  );

  // ── Step 5: Get Moz Metrics ──────────────────────────────────────────────
  let domainAuthority = 0;
  let spamScore = 0;

  try {
    logger.info(`  Fetching Moz metrics…`);
    const mozData = await getMozMetrics(discoveredUrl);
    domainAuthority = mozData.domainAuthority;
    spamScore = mozData.spamScore;
    logger.info(`  Moz metrics retrieved — DA: ${domainAuthority}, Spam: ${spamScore}`);
  } catch (err) {
    logger.warn(
      `  Moz metrics failed — defaulting to 0 (${err instanceof Error ? err.message : "unknown error"})`
    );
  }

  const daCategoryStr   = categorizeDa(domainAuthority);
  logger.info(`  DA: ${domainAuthority} → category: ${daCategoryStr}`);

  // ── Step 6: Save to database ───────────────────────────────────────────────
  const websiteInput = {
    name:            crawl.title || discoveredTitle,
    url:             crawl.url   || discoveredUrl,
    description:     crawl.description,
    domainAuthority,
    spamScore,
    estimatedTraffic: Math.floor(Math.random() * 5000), // Placeholder for traffic API
    contactEmail:    crawl.email,
    socialLinks:     crawl.socials as any,
    freeListing,
    industry:        classification.industry,
    daCategory:      daCategoryStr as DaCategory,
    active:          true,
  };

  let savedId = `pending-${index}`;

  if (!dryRun) {
    try {
      console.log("Saving website:", websiteInput.url);
      const saved = await saveDiscoveredWebsite(websiteInput);
      savedId = saved.id;
      console.log("Saved website:", savedId);
    } catch (err) {
      logger.warn(
        `  DB save skipped — ${err instanceof Error ? err.message : "unknown error"}`
      );
    }
  } else {
    logger.info(`  Dry run — skipping database save`);
  }

  return {
    id:             savedId,
    name:           websiteInput.name,
    url:            websiteInput.url,
    description:    websiteInput.description || null,
    domainAuthority,
    spamScore,
    freeListing,
    industry:       classification.industry,
    daCategory:     daCategoryStr,
    estimatedTraffic: websiteInput.estimatedTraffic,
    contactEmail:    websiteInput.contactEmail || null,
    socialLinks:     websiteInput.socialLinks,
    active:         true,
  };
}

export async function runDiscoveryPipeline(
  keyword: string,
  options: PipelineOptions = {}
): Promise<PipelineReport> {
  const { dryRun = false } = options;
  const startedAt = new Date();

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Search started — keyword: "${keyword}"`);
  if (dryRun) logger.info(`Dry run — database writes disabled`);
  logger.info(`══════════════════════════════════════════`);

  // ── Step 1: Discover website URLs ──────────────────────────────────────────
  logger.info(`Step 1 — Discovering websites…`);

  console.log(`Search started (Step 1): "${keyword}"`);
  let discovery;
  try {
    discovery = await discoverWebsites(keyword);
    logger.info(`Selected provider: ${discovery.provider}`);
    logger.info(`Search queries: ${discovery.queries.join(" | ")}`);
    console.log(`Discovered websites: ${discovery.results.length} using ${discovery.provider} provider`);
    console.log(`URLs discovered: ${discovery.results.map((item) => item.url).join(" | ")}`);
    logger.info(`Websites discovered — ${discovery.results.length} URL(s)`);
  } catch (err) {
    logger.error(
      `Step 1 failed — ${err instanceof Error ? err.message : "unknown error"}`
    );
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      "none",
      isFallback:  false,
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }

  if (discovery.results.length === 0) {
    logger.warn(`No URLs discovered — pipeline complete with zero results`);
    return {
      keyword,
      discovered:  0,
      processed:   0,
      saved:       0,
      failed:      0,
      results:     [],
      source:      discovery.provider,
      isFallback:  discovery.provider === "mock" || discovery.provider === "directory-fallback",
      startedAt:   formatDateSafe(startedAt),
      completedAt: formatDateSafe(new Date()),
    };
  }
  console.log("Discovered websites:", discovery.results.length);

  // ── Steps 2–6: Process URLs with throttled concurrency mapping ──────────────────
  logger.info(
    `Steps 2–6 — Processing ${discovery.results.length} URL(s) with concurrency limit 3 and staggering…`
  );

  let rawResults: (PipelineResult | null)[] = [];

  try {
    // Process ALL results with a concurrency limit of 3 (as per previous audit's log)
    rawResults = await mapConcurrent(discovery.results, 3, async (item, i) => {
      logger.info(`Starting processUrl for ${item.url} (item ${i + 1}/${discovery.results.length})`);
      return processUrl(item.url, item.title, i + 1, discovery.results.length, dryRun);
    });
  } finally {
    // ── Cleanup: close the shared Playwright browser ───────────────────────────
    await closeBrowser();
    logger.info(`Browser closed`);
  }

  const successful = rawResults.filter(r => r !== null);
  logger.info(`Crawled websites — ${successful.length}/${discovery.results.length}`);
  
  const results: PipelineResult[] = [];
  let saved  = 0;
  let failed = 0;

  for (const result of rawResults) {
    if (result !== null) {
      results.push(result);
      if (!result.id.startsWith("pending-")) {
        saved++;
      }
    } else {
      failed++;
    }
  }

  const completedAt = new Date();
  const durationMs  = completedAt.getTime() - startedAt.getTime();

  // Diagnostics calculations
  const providerSelected = discovery.provider;
  const urlsDiscoveredCount = discovery.results.length + (discovery.filteredCount || 0);
  const urlsFilteredCount = discovery.filteredCount || 0;
  const urlsCrawledCount = discovery.results.length;
  const urlsSavedCount = saved;
  const crawlSuccessRatePercent = urlsCrawledCount > 0 ? Math.round((successful.length / urlsCrawledCount) * 100) : 0;
  const saveSuccessRatePercent = successful.length > 0 ? Math.round((saved / successful.length) * 100) : 0;

  console.log(`\n==================================================`);
  console.log(`[Pipeline Diagnostics]`);
  console.log(`- Provider Selected: ${providerSelected}`);
  console.log(`- URLs Discovered: ${urlsDiscoveredCount}`);
  console.log(`- URLs Filtered: ${urlsFilteredCount}`);
  console.log(`- URLs Crawled: ${urlsCrawledCount}`);
  console.log(`- URLs Saved: ${urlsSavedCount}`);
  console.log(`- Crawl Success Rate: ${crawlSuccessRatePercent}%`);
  console.log(`- Save Success Rate: ${saveSuccessRatePercent}%`);
  console.log(`==================================================\n`);

  logger.info(`══════════════════════════════════════════`);
  logger.info(`Results returned — ${results.length} websites`);
  logger.info(`Pipeline complete in ${durationMs}ms`);
  logger.info(`══════════════════════════════════════════`);

  return {
    keyword,
    discovered:  discovery.results.length,
    processed:   results.length,
    saved,
    failed,
    results,
    source:      discovery.provider,
    isFallback:  discovery.provider === "mock" || discovery.provider === "directory-fallback",
    startedAt:   formatDateSafe(startedAt),
    completedAt: formatDateSafe(completedAt),
    diagnostics: {
      providerSelected,
      urlsDiscoveredCount,
      urlsFilteredCount,
      urlsCrawledCount,
      urlsSavedCount,
      crawlSuccessRatePercent,
      saveSuccessRatePercent,
    }
  };
}
